include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated_plugin_registrant.dart]

linter:
  rules:
    # Util classes
    avoid_classes_with_only_static_members: false

    non_constant_identifier_names: false

    constant_identifier_names: false

    no_leading_underscores_for_local_identifiers: false

    library_private_types_in_public_api: false

    depend_on_referenced_packages: false

    use_build_context_synchronously: false
