include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated_plugin_registrant.dart]

language:
   strict-interference: true
   strict-raw-types: true

errors:
  missing_required_param: error
  missing_return: error
  dead_code: error
  unused_element: error
  unused_import: error
  unused_local_variable: error

linter:
  rules:
    # Util classes
    avoid_classes_with_only_static_members: false

    non_constant_identifier_names: false

    constant_identifier_names: false

    camel_case_types: true

    empty_statements: true
  