include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated_plugin_registrant.dart]

linter:
  rules:
    # Util classes
    avoid_classes_with_only_static_members: false

    avoid_redundant_argument_values: false

    constant_identifier_names: false
