include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated_plugin_registrant.dart]

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: false

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes
    avoid_classes_with_only_static_members: false

    avoid_redundant_argument_values: false

    join_return_with_assignment: false

    non_constant_identifier_names:  false

    constant_identifier_names: false
