include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/generated_plugin_registrant.dart]

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: false

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes
    avoid_classes_with_only_static_members: false

    avoid_redundant_argument_values: false

    # Unnecessary use of this in constructors should not be done
    unnecessary_this: false

    leading_newlines_in_multiline_strings: false

    type_annotate_public_apis: false
    
    directives_ordering: false

    avoid_function_literals_in_foreach_calls: false

    join_return_with_assignment: false

    #prefer_function_declarations_over_variables: false

    #prefer_const_constructors

    non_constant_identifier_names:  false

    constant_identifier_names: false

    prefer_typing_uninitialized_variables: false
