# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Override TOCropViewController to use the main branch
  # Note: The main branch still contains deprecated UIViewLayoutRegion APIs
  # that were removed in iOS 18 SDK (Xcode 16+). These are patched out
  # automatically in the post_install hook below.
  # See: https://github.com/TimOliver/TOCropViewController
  pod 'TOCropViewController', :git => 'https://github.com/TimOliver/TOCropViewController.git', :branch => 'main'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Set minimum deployment target to iOS 14.0 for all pods
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
  
  # Patch TOCropViewController to remove deprecated UIViewLayoutRegion APIs
  # These APIs were removed in iOS 18 SDK (Xcode 16+)
  tocrop_file = 'Pods/TOCropViewController/Objective-C/TOCropViewController/TOCropViewController.m'
  if File.exist?(tocrop_file)
    text = File.read(tocrop_file)
    # Comment out the problematic UIViewLayoutRegion code
    new_text = text.gsub(
      /    \/\/ fix: On iOS 26, overlay with iPadOS windowingControl area\.\n    if \(@available\(iOS 26\.0, \*\)\) \{\n      if \(!verticalLayout\) \{\n#if __IPHONE_OS_VERSION_MAX_ALLOWED < 180000\n        UIViewLayoutRegion \*layoutRegion = \[UIViewLayoutRegion safeAreaLayoutRegionWithCornerAdaptation: UIViewLayoutRegionAdaptivityAxisVertical\];\n        UIEdgeInsets edgeInsets = \[self\.view edgeInsetsForLayoutRegion:layoutRegion\];\n        insets\.top = edgeInsets\.top;\n        insets\.left = edgeInsets\.left;\n        insets\.bottom = edgeInsets\.bottom;\n#endif\n      \}\n    \}/,
      "    // fix: On iOS 26, overlay with iPadOS windowingControl area.\n    // Note: UIViewLayoutRegion APIs were removed in iOS 18 SDK (Xcode 16+)\n    // Commenting out this code as it uses deprecated APIs\n    // if (@available(iOS 26.0, *)) {\n    //   if (!verticalLayout) {\n    // #if __IPHONE_OS_VERSION_MAX_ALLOWED < 180000\n    //     UIViewLayoutRegion *layoutRegion = [UIViewLayoutRegion safeAreaLayoutRegionWithCornerAdaptation: UIViewLayoutRegionAdaptivityAxisVertical];\n    //     UIEdgeInsets edgeInsets = [self.view edgeInsetsForLayoutRegion:layoutRegion];\n    //     insets.top = edgeInsets.top;\n    //     insets.left = edgeInsets.left;\n    //     insets.bottom = edgeInsets.bottom;\n    // #endif\n    //   }\n    // }"
    )
    if text != new_text
      File.open(tocrop_file, 'w') { |file| file.write(new_text) }
      puts "✓ Patched TOCropViewController to remove deprecated UIViewLayoutRegion APIs"
    end
  end
end
