# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

def parse_KV_file(file,seperator='=')
  file_abs_path = File.expand_path(file)
  return [] unless File.exist? file_abs_path

  pods_ary = []
  skip_line_start_symbols = ['#', '/']
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }

    plugin = line.split(seperator)
    if plugin.length == 2
      podname = plugin[0].strip
      path = plugin[1].strip
      podpath = File.expand_path(path.to_s, file_abs_path)
      pods_ary.push({ name: podname, path: podpath })
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  pods_ary
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, execute flutter build/run first."
  end
  generated_xcode_build_settings.map do |p|
    pod 'Flutter', path: p[:path] if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
  end

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map do |p|
    pod p[:name], path: File.expand_path('ios', p[:path])
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
